<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_UsernameForgot</name>
   <tag></tag>
   <elementGuidId>535cd73b-eb79-4d9b-8685-723d5dbf5003</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='securityAuthentication_userName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#securityAuthentication_userName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d68f37e-bcfb-4079-92d5-b850934ae857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6beeaeaa-df16-4e3f-aa66-ec5cbc8bf59f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>securityAuthentication[userName]</value>
      <webElementGuid>4716dfe8-5257-44f5-9e52-2349ddbf0e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>securityAuthentication_userName</value>
      <webElementGuid>1cbdd654-b516-4fce-aa59-d9091807453f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;securityAuthentication_userName&quot;)</value>
      <webElementGuid>67bbb866-65f1-4df6-9064-dcfc74bd9b06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='securityAuthentication_userName']</value>
      <webElementGuid>180d7030-1103-48ad-a530-95beb6453192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='resetPasswordForm']/fieldset/ol/li/input</value>
      <webElementGuid>01ba128a-c360-4740-a87c-d70b851146de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>503f2069-926a-41a1-9995-fb2e3e4e571f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'securityAuthentication[userName]' and @id = 'securityAuthentication_userName']</value>
      <webElementGuid>8a5a8d9c-4d9f-4a33-83e3-f8486624e5e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
